
- name: Создание пользователя
  raw: |
    sudo -u postgres psql -c "CREATE USER {{ postgresql_settings.db_user }} WITH PASSWORD '{{ postgresql_settings.db_pass }}';"
  become: yes
  ignore_errors: yes

- name: Создание базы даныых
  raw: |
    sudo -u postgres psql -c "CREATE DATABASE {{ postgresql_settings.db_name }} OWNER {{ postgresql_settings.db_user }};"
  become: yes
  ignore_errors: yes

- name: Создание пользователя для репликации
  raw: |
    sudo -u postgres psql -c "CREATE ROLE {{ postgresql_settings.db_repl_user }} WITH REPLICATION LOGIN PASSWORD '{{ postgresql_settings.db_repl_pass }}'";
  become: yes
  ignore_errors: yes

- name: Конфигурация postgresql.conf
  ansible.builtin.blockinfile:
    path: /etc/postgresql/14/main/postgresql.conf
    block: |
      listen_addresses = '*'
      wal_level = replica
    state: present
  ignore_errors: yes

- name: Конфигурация pg_hba.conf
  ansible.builtin.template:
    src: pg_hba.j2
    dest: /etc/postgresql/14/main/pg_hba.conf

- name: Перезапуск PostgreSQL сервера
  ansible.builtin.systemd:
    name: postgresql
    state: restarted
