---
linux:  # Группа хостов
  children:  # Обозначение, что будет подгруппа хостов
    all_hosts:
      hosts:
        nginx-balancer:
          ansible_host: "{{ nginx_balancer_ip.public }}"
          ansible_local: "{{ nginx_balancer_ip.local }}"
        nginx-server-1:
          ansible_host: "{{ nginx_server_1_ip.public }}"
          ansible_local: "{{ nginx_server_1_ip.local }}"
        nginx-server-2:
          ansible_host: "{{ nginx_server_2_ip.public }}"
          ansible_local: "{{ nginx_server_1_ip.local }}"
        backup_server_1:
          ansible_host: "{{ backup_server_ip.public }}"
          ansible_local: "{{ backup_server_ip.local }}"
        postgresql_master:
          ansible_host: "{{ postgresql_master_ip.public }}"
          ansible_local: "{{ postgresql_master_ip.local }}"
    nginx-balancer:
      hosts:
        nginx-balancer:
          ansible_host: "{{ nginx_balancer_ip.public }}"
          ansible_local: "{{ nginx_balancer_ip.local }}"
    nginx-server:
      hosts:
        nginx-balancer:
          ansible_host: "{{ nginx_balancer_ip.public }}"
          ansible_local: "{{ nginx_balancer_ip.local }}"
        nginx-server-1:
          ansible_host: "{{ nginx_server_1_ip.public }}"
          ansible_local: "{{ nginx_server_1_ip.local }}"
        nginx-server-2:
          ansible_host: "{{ nginx_server_2_ip.public }}"
          ansible_local: "{{ nginx_server_2_ip.local }}"
    nginx-mediawiki:
      hosts:
        nginx-server-1:
          ansible_host: "{{ nginx_server_1_ip.public }}"
          ansible_local: "{{ nginx_server_1_ip.local }}"
        nginx-server-2:
          ansible_host: "{{ nginx_server_2_ip.public }}"
          ansible_local: "{{ nginx_server_2_ip.local }}"
    postgresql:
      hosts:
        postgresql_master:
          ansible_host: "{{ postgresql_master_ip.public }}"
          ansible_local: "{{ postgresql_master_ip.local }}"
        postgresql_replica:
          ansible_host: "{{ postgresql_replica.public }}"
          ansible_local: "{{ postgresql_replica.local }}"
    postgresql_master:
      hosts:
        postgresql_master:
          ansible_host: "{{ postgresql_master_ip.public }}"
          ansible_local: "{{ postgresql_master_ip.local }}"
    postgresql_replica:
      hosts:
        postgresql_replica:
          ansible_host: "{{ postgresql_replica.public }}"
          ansible_local: "{{ postgresql_replica.local }}"
    backup_server:
      hosts:
        backup_server_1:
          ansible_host: "{{ backup_server_ip.public }}"
          ansible_local: "{{ backup_server_ip.local }}"

  vars:  # Переменные, доступные или используемые для всех подгрупп
    ansible_user: "ubuntu"
    #ansible_password: "qwerty"
    connection_protocol: ssh  # тип подключения
    ansible_become: true  # Становиться ли другим пользователем после подключения
    ansible_become_user: root
    nginx_balancer_ip:
      public: 89.169.128.79
      local: 192.168.10.34
    nginx_server_1_ip:
      public: 89.169.133.85
      local: 192.168.10.9
    nginx_server_2_ip:
      public: 158.160.55.213
      local: 192.168.10.32
    postgresql_master_ip:
      public: 158.160.38.118
      local: 192.168.10.36
    backup_server_ip:
      public: 158.160.39.253
      local: 192.168.10.11
    postgresql_replica:
      public: 51.250.11.143
      local: 192.168.10.13
