- name: Настройка postgresql master
  hosts: postgresql-master
  roles:
   - role: config_postgresql_master


- name: Создание postgresql replica
  hosts: postgresql-replica
  roles:
    - role: config_postgresql_replica
  vars_files:
    - postgresql_vars/main.yml

